"""
常量模組

提供系統各模組使用的常量定義。
"""

from .enums import Department
from .attendance import (
    LEAVE_PATTERNS,
    R_SHIFT_PATTERN,
    NATIONAL_HOLIDAY_PATTERN,
    OVERTIME_PATTERN,
    OVERTIME_CODE_MAP,
    OVERTIME_POINTS_MAP,
    A_SERIES_POINTS,
    M_SERIES_POINTS,
    EMPLOYEE_ID_COLUMN_ALIASES,
    EMPLOYEE_NAME_COLUMN_ALIASES,
)

__all__ = [
    "Department",
    "LEAVE_PATTERNS",
    "R_SHIFT_PATTERN",
    "NATIONAL_HOLIDAY_PATTERN",
    "OVERTIME_PATTERN",
    "OVERTIME_CODE_MAP",
    "OVERTIME_POINTS_MAP",
    "A_SERIES_POINTS",
    "M_SERIES_POINTS",
    "EMPLOYEE_ID_COLUMN_ALIASES",
    "EMPLOYEE_NAME_COLUMN_ALIASES",
]
